In [160]:
import pandas as pd # 데이터 분석에서 자주 사용되는 라이브 러리
import numpy as np # # 다양한 계산을 빠르게 수행하게 돕는 라이브러리
import matplotlib.pyplot as plt # 시각화 라이브러리
import seaborn as sns # 시각화 라이브러리
import scipy.stats as stats # 통계 계산 라이브러리

In [161]:
df = pd.read_csv('D:\AutoBackUp\Downloads\GMG.2.csv')

<>:1: SyntaxWarning: invalid escape sequence '\A'
<>:1: SyntaxWarning: invalid escape sequence '\A'
C:\Users\Admin\AppData\Local\Temp\ipykernel_19388\690671193.py:1: SyntaxWarning: invalid escape sequence '\A'
  df = pd.read_csv('D:\AutoBackUp\Downloads\GMG.2.csv')


In [162]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 901097 entries, 0 to 901096
Data columns (total 24 columns):
 #   Column           Non-Null Count   Dtype  
---  ------           --------------   -----  
 0   visitNumber      901097 non-null  int64  
 1   visitId          901097 non-null  int64  
 2   visitStartTime   901097 non-null  int64  
 3   date             901097 non-null  int64  
 4   pageviews        900997 non-null  float64
 5   timeOnSite       450584 non-null  float64
 6   source           901097 non-null  object 
 7   medium           901097 non-null  object 
 8   keyword          241900 non-null  object 
 9   browser          901097 non-null  object 
 10  operatingSystem  901097 non-null  object 
 11  deviceCategory   901097 non-null  object 
 12  subContinent     901097 non-null  object 
 13  country          901097 non-null  object 
 14  city             901097 non-null  object 
 15  networkDomain    901097 non-null  object 
 16  hit_hour         901097 non-null  int6

In [163]:
df.isnull().sum()

visitNumber             0
visitId                 0
visitStartTime          0
date                    0
pageviews             100
timeOnSite         450513
source                  0
medium                  0
keyword            659197
browser                 0
operatingSystem         0
deviceCategory          0
subContinent            0
country                 0
city                    0
networkDomain           0
hit_hour                0
isInteraction           0
pageTitle             153
pagePath                0
productCategory    664512
promoName          627873
promoPosition      627873
channelGrouping         0
dtype: int64

# 컬럼 확인

In [164]:
df['pagePath'].unique()

array(['/home', '/google+redesign/office',
       '/google+redesign/electronics/audio/google+g+noise+reducing+bluetooth+headphones.axd',
       ...,
       '/google+redesign/apparel/men+s+google+full+zip+fleece+2x.axd',
       '/google+redesign/office/writing/bic+anthem+pen.axd',
       '/google+redesign/brands/go/go+gopher+messenger+bag.axd'],
      shape=(1283,), dtype=object)

In [165]:
filtered_df = df[df['pagePath'].str.contains('home', na=False)]
print(filtered_df['pagePath'])

0         /home
1         /home
2         /home
4         /home
5         /home
          ...  
901091    /home
901093    /home
901094    /home
901095    /home
901096    /home
Name: pagePath, Length: 627910, dtype: object


In [166]:
df['pageTitle'].unique()

array(['Google Online Store', 'Home', 'Office | Google Merchandise Store',
       'The Google Merchandise Store/Google G Noise-reducing Bluetooth Headphones',
       'Electronics',
       'Home|https://shop.googlemerchandisestore.com/?utm_source=Partners&utm_medium=affiliate&utm_campaign=Data%20Share%20Promo',
       'Android', 'The Google Merchandise Store - Register',
       'Home - https://shop.googlemerchandisestore.com/?utm_source=Partners&utm_medium=affiliate&utm_campaign=Data%20Share%20Promo',
       "Men's Outerwear | Apparel | Google Merchandise Store",
       'Store search results',
       'Audio | Electronics | Google Merchandise Store',
       'Drinkware | Google Merchandise Store', 'Shipping Information',
       "Men's", 'Shopping Cart',
       'Water Bottles & Tumblers | Drinkware | Google Merchandise Store',
       'Drinkware', 'Office', "Men's-T-Shirts",
       'Backpacks | Bags | Google Merchandise Store',
       "Men's Apparel | Google Merchandise Store",
       'The 

In [167]:
df['browser'].unique()

array(['Safari', 'Chrome', 'Android Webview', 'Firefox',
       'Internet Explorer', 'Edge', 'Safari (in-app)', 'Opera Mini',
       'Android Browser', 'UC Browser', 'YaBrowser', 'Opera',
       'Nintendo Browser', 'Mozilla Compatible Agent', 'Seznam',
       'LYF_LS_4002_12', 'Puffin', '0', 'IE with Chrome Frame', 'Maxthon',
       'Amazon Silk', 'MRCHROME', 'BlackBerry', 'SeaMonkey',
       'Nokia Browser', 'Coc Coc', 'MQQBrowser', 'Hisense M20-M_LTE',
       'LYF_LS_4002_11', 'Lunascape', 'Mozilla', 'Iron', 'Nichrome',
       'DASH_JR_3G', 'Konqueror', 'no-ua', '(not set)', 'Reddit',
       'Apple-iPhone7C2', 'NokiaE52-1',
       '[Use default User-agent string] LIVRENPOCHE',
       'osee2unifiedRelease', 'ThumbSniper', 'YE', 'Android Runtime',
       'CSM Click', 'subjectAgent: NoticiasBoom', 'User Agent',
       'Changa 99695759', 'M5', 'HTC802t_TD', 'ADM', 'TCL P500M',
       'DoCoMo'], dtype=object)

In [168]:
df['pageviews'].unique()

array([  1.,   2.,   8.,   5.,   3.,  13.,   7.,   6.,  11.,   4.,  12.,
        10.,  14.,  28.,   9.,  25.,  15.,  18.,  19.,  23.,  20.,  30.,
        16.,  22.,  17.,  26.,  40.,  21.,  45.,  37.,  36.,  35.,  42.,
        41.,  66., 185.,  29.,  43.,  55.,  32.,  31.,  24.,  48., 224.,
        70.,  38., 188., 143.,  33.,  67.,  80.,  49.,  50.,  65.,  78.,
        34.,  27.,  92.,  54.,  53.,  46.,  64.,  63.,  39., 112.,  57.,
        44.,  47., 162., 169.,  51.,  58.,  59.,  89., 106.,  56.,  74.,
        52., 145.,  79.,  61.,  nan,  60.,  69.,  75., 104., 113.,  98.,
        72., 429.,  88.,  81.,  62.,  71., 132.,  90.,  86., 122.,  73.,
       118.,  91.,  76.,  97., 343.,  85., 100., 138., 120.,  84., 223.,
       103., 146.,  68.,  87.,  82., 111., 300.,  96.,  83., 115., 117.,
       130., 110., 191.,  99., 131., 148.,  93., 220., 128., 116., 102.,
        77., 108., 165., 324.,  94., 275., 189., 305., 135.,  95., 175.,
       210., 105., 114., 139., 109., 123., 167., 14

In [169]:
df['timeOnSite'].unique()

array([  nan,    9.,  278., ..., 3211., 6468., 7667.], shape=(4256,))

In [170]:
df['source'].unique()

array(['(direct)', 'Partners', 'google', '(not set)', 'dfa', 'baidu',
       'ask', 'yahoo', 'bing', 'images.google', 'gophergala.com',
       'search.mysearch.com', 'google.com', 'analytics.google.com',
       'hangouts.google.com', 'blog.golang.org', 'm.baidu.com',
       'dealspotr.com', 'au.search.yahoo.com', 'google.com.au',
       'productforums.google.com', 'duckduckgo.com', 'seroundtable.com',
       'siliconvalley.about.com', 'connect.googleforwork.com',
       'mail.google.com', 'h.yandex-team.ru', 'online-metrics.com',
       'docs.google.com', 'mg.mail.yahoo.com', 'sites.google.com',
       'phandroid.com', 'googleads.g.doubleclick.net',
       'int.search.tb.ask.com', 'wap.sogou.com', 'away.vk.com',
       'm.sogou.com', 'google.com.co', 'support.google.com',
       'images.google.fr', 'google.de', 'images.google.de',
       'startpage.com', 'ixquick.com', 'google.gr', 'adwords.google.com',
       'google.co.in', 'in.search.yahoo.com', 'lunametrics.com',
       'google.co.

In [171]:
df['medium'].unique()

array(['(none)', '(not set)', 'affiliate', 'cpm', 'organic', 'cpc',
       'referral'], dtype=object)

In [172]:
df['keyword'].unique()

array([nan, 'youtube t shirt', '(not provided)', ..., 'yputbu',
       '+woman shades', 'google accessories store'],
      shape=(2718,), dtype=object)

In [173]:
df['operatingSystem'].unique()

array(['Macintosh', 'Windows', 'Android', 'Linux', 'iOS', 'Chrome OS',
       '(not set)', 'Windows Phone', 'Samsung', 'Nintendo WiiU',
       'Nintendo Wii', 'BlackBerry', 'Firefox OS', 'Xbox', 'OpenBSD',
       'FreeBSD', 'Nokia', 'Nintendo 3DS', 'SunOS', 'NTT DoCoMo'],
      dtype=object)

In [174]:
df['deviceCategory'].unique()

array(['desktop', 'mobile', 'tablet'], dtype=object)

In [175]:
df['subContinent'].unique()

array(['Western Europe', 'Eastern Africa', 'Northern America',
       '(not set)', 'South America', 'Western Asia', 'Australasia',
       'Southern Asia', 'Eastern Europe', 'Middle Africa', 'Eastern Asia',
       'Southern Europe', 'Northern Europe', 'Northern Africa',
       'Western Africa', 'Southeast Asia', 'Central Asia',
       'Central America', 'Southern Africa', 'Caribbean', 'Melanesia',
       'Micronesian Region', 'Polynesia'], dtype=object)

In [176]:
df['country'].unique()

array(['Belgium', 'Kenya', 'United States', '(not set)', 'Argentina',
       'Armenia', 'Australia', 'Austria', 'Bahrain', 'Bangladesh',
       'Brazil', 'Bulgaria', 'Cameroon', 'Canada', 'Chile', 'China',
       'Colombia', 'Croatia', 'Czechia', 'Denmark', 'Ecuador', 'Egypt',
       'Estonia', 'Finland', 'France', 'Germany', 'Ghana', 'Greece',
       'Hong Kong', 'Hungary', 'India', 'Indonesia', 'Ireland', 'Israel',
       'Italy', 'Japan', 'Jordan', 'Kazakhstan', 'Lebanon', 'Libya',
       'Lithuania', 'Luxembourg', 'Macau', 'Malaysia', 'Mexico',
       'Moldova', 'Mongolia', 'Myanmar (Burma)', 'Netherlands',
       'New Zealand', 'Nigeria', 'Norway', 'Pakistan', 'Panama',
       'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Romania',
       'Russia', 'Saudi Arabia', 'Singapore', 'Slovakia', 'Slovenia',
       'South Africa', 'South Korea', 'Spain', 'Sri Lanka', 'Sweden',
       'Switzerland', 'Taiwan', 'Thailand', 'Turkey', 'Ukraine',
       'United Arab Emirates', 'Unit

In [177]:
df['city'].unique()

array(['Brussels', 'not available in demo dataset', 'Seattle',
       '(not set)', 'Buenos Aires', 'Mar del Plata', 'Pinamar', 'Sydney',
       'Melbourne', 'Sao Paulo', 'Toronto', 'Montreal', 'Vancouver',
       'Santiago', 'Bogota', 'Zagreb', 'Brno', 'Prague', 'Roskilde',
       'Odense', 'Tampere', 'Paris', 'Frankfurt', 'Berlin', 'Hamburg',
       'Athens', 'Hong Kong', 'Budapest', 'Kolkata', 'Mumbai',
       'Bengaluru', 'Chennai', 'Pune', 'Hyderabad', 'New Delhi',
       'Ahmedabad', 'Bandung', 'Surabaya', 'Dublin', 'Tel Aviv-Yafo',
       'Milan', 'Chuo', 'Minato', 'Shibuya', 'Shinjuku', 'Amã', 'Nairobi',
       'Kuala Lumpur', 'Petaling Jaya', 'Mexico City', 'Monterrey',
       'Schagen', 'Amsterdam', 'Utrecht', 'Auckland', 'Karachi', 'Taguig',
       'Warsaw', 'Poznan', 'Lisbon', 'Saint Petersburg', 'Petergof',
       'Moscow', 'Singapore', 'Seoul', 'Seville', 'Barcelona', 'Madrid',
       'Valencia', 'Malaga', 'Elche', 'Stockholm', 'Gothenburg',
       'Bangkok', 'Istanbul', '

In [178]:
df['networkDomain'].unique()

array(['unknown.unknown', 'arso-oran.org', '(not set)', ...,
       'maisonjsc.com', 'somotweb2.com', 'bravo.com.vn'],
      shape=(28012,), dtype=object)

In [179]:
df['hit_hour'].unique()

array([ 6,  0, 12, 17,  3, 18, 14, 10, 16,  2, 19, 11, 21, 22, 23,  1,  9,
       15,  8,  5, 13,  7,  4, 20])

In [180]:
df['isInteraction'].unique()

array([ True])

In [181]:
df['channelGrouping'].unique()

array(['(Other)', 'Affiliates', 'Direct', 'Display', 'Organic Search',
       'Paid Search', 'Referral', 'Social'], dtype=object)

# 데이터 전처리

In [182]:
df = df.dropna(subset=['pageTitle'])
print(df_clean)

        visitNumber     visitId  visitStartTime      date  pageviews  \
0                 3  1479737678      1479737678  20161121        1.0   
1                 6  1484727530      1484727530  20170118        1.0   
2                 3  1491508010      1491508010  20170406        2.0   
3                 9  1492302990      1492302990  20170415        1.0   
4                 1  1485431224      1485431224  20170126        2.0   
...             ...         ...             ...       ...        ...   
901092            1  1501057233      1501057233  20170726        1.0   
901093            1  1490041442      1490041442  20170320        1.0   
901094            1  1471890172      1471890172  20160822        1.0   
901095            1  1490987524      1490987524  20170331        2.0   
901096            1  1474357112      1474357112  20160920        1.0   

        timeOnSite       source     medium keyword     browser  ...  \
0              NaN     (direct)     (none)     NaN      Safari  

In [183]:
df['pageTitle'].isnull().sum()

np.int64(0)

In [184]:
df['pagePath'] = df['pagePath'].fillna('')        # NaN → 빈 문자열 처리
df['pagePath'] = df['pagePath'].str.count('/')

In [185]:
print(df['pagePath'])

0         1
1         1
2         1
3         2
4         1
         ..
901092    3
901093    1
901094    1
901095    1
901096    1
Name: pagePath, Length: 900944, dtype: int64


In [187]:
df['pagePath'].unique()

array([ 1,  2,  4,  3,  5, 16, 11, 10, 15, 14, 17, 12,  8,  6, 13, 19,  7,
        9, 18, 20])